# Generated by Django 5.2.17 on 2026-09-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('length', models.DecimalField(decimal_places=2, help_text='Internal length in cm', max_digits=8)),
                ('width', models.DecimalField(decimal_places=2, help_text='Internal width in cm', max_digits=8)),
                ('height', models.DecimalField(decimal_places=2, help_text='Internal height in cm', max_digits=8)),
                ('max_weight', models.DecimalField(decimal_places=2, help_text='Max weight capacity in kg', max_digits=8)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Box unit cost', max_digits=8)),
            ],
            options={
                'ordering': ['cost'],
            },
        ),
    ]
